### ISSUE TITLE
Adding new hardware wallet: BitBox02

### ISSUE THREAD

**Issue by NickeZ** [shapeshift/hdwallet#128]
Hey!

What do you think about adding support for [BitBox02](https://shiftcrypto.ch/bitbox02/)?

We (Shift Cryptosecurity) have been around since 2015 and we have had two successful products in this space: the "Digital BitBox" and the "BitBox02". Both have been listed by bitcoin.org and you can currently find the BitBox02 there: https://bitcoin.org/en/wallets/hardware/bitbox/?step=5&platform=hardware

Recently we developed support for web wallets. We take a similar route to it as Trezor and require the user to install a bridge for usb to http communication. But we never redirect the user to anything hosted by us, so we can't collect metadata about the users. The communication is also end-to-end encrypted between the web service and our hardware wallet. Our bridge is open source and available [here](https://github.com/digitalbitbox/bitbox-bridge/releases/tag/v1.0.1).

You can see how integration would look like in our npm package [here](https://github.com/digitalbitbox/bitbox02-api-js/blob/master/demo/demo.js). We are working on improving the demo to make it the documentation of how to do integrations.

What do you think?

**Comment by jjfarrow** [comment]
Hello, and thanks for your interest in adding a wallet to the hdwallet open source library! We would welcome a pull request from you to get it added. You can see more about our policies here: https://pages.shapeshift.com/developer-portal/ Cheers!

**Comment by mrnerdhair** [comment]
Closing this as stale; we'd still welcome a PR for this. Drop into https://discord.gg/shapeshift if you want to chat about it!
