### ISSUE TITLE
Please List Charg Coin (CHG)

### ISSUE THREAD

**Issue by stealthmachines** [shapeshift/hdwallet#149]
Please list Charg Coin (CHG).  Since 2017, Charg Coin (CHG) has been democratizing the price of energy-time.  

1) We have our own mainnet, located here:
 https://stats.chgcoin.org
https://explorer.chgcoin.org
https://hub.chgcoin.org

2) Even though we have our own POA golang mainnet, the new mainnet supports the old ERC20, and CHG can live on EITHER blockchain with cap of 90MM CHG across both.  For example, it 45MM CHG is living on the ERC20 chain, only 45MM CHG can live on the mainnet at that exact moment in time.

3) Our ERC20 information for the listing is as follows.  Since our mainnet supports the ERC20, we only require you to list the ERC20 for the time being:
A) Contract address: 0x482EFd447bE88748e7625e2b7c522c388970B790
B) Name: Charg Coin
C) ticker: CHG
D) # of digits: 18

3) We have 50K facebook likes here - https://www.facebook.com/ChargCoin/
and another 9K facebook likes for wecharg, located here - https://www.facebook.com/WeCharg.Official/

4) Our websites are as follows:
https://chgcoin.org (main website)
https://wecharg.com (use case / partner company)
https://forum.chgcoin.org
https://t.me/chargchat

**Comment by BitHighlander** [comment]
We will be adding support for https://tokenlists.org/ soon. this has been added to our list for out tokenlist. thanks
