### ISSUE TITLE
Electron Support

### ISSUE THREAD

**Issue by chaindbkey** [shapeshift/hdwallet#229]
I was about to use this lib for ledger device connection and found a problem.
It works in web but not in electron. I'm getting following issue when call pairDevice method.

> WebUSBCouldNotPair: Could not pair Ledger: Failed to execute 'requestDevice' on 'USB': Must be handling a user gesture to show a permission request.

So I digged into it and noticed that this lib uses "@ledgerhq/hw-transport-webusb" which is not supported in electron.
Did I miss something or is it in progress or future plan?

**Comment by reidrankin** [comment]
Closed (finally!) by #29. Examples are still to-do, but if you need this ASAP ping me for a walkthrough.

**Comment by BitHighlander** [comment]
as of version 1.15.2 we have electron support. see https://github.com/shapeshift/hdwallet/tree/master/packages/hdwallet-keepkey-electron ✔️
