### ISSUE TITLE
Recovery functionality throws error on button clicking

### ISSUE THREAD

**Issue by ryaben** [shapeshift/hdwallet#242]
I wiped my KeepKey, and when tried to recover a seed the platform was unable to carry out the process. The buttons from the virtual keyboard that the user must use to input the recovery seed are not working and retrieving an error via console. I'm attaching a couple of gifs about my experience so this can be more clear. Looks like a global issue, I've attempted to do so in Chrome, Edge and Brave, all resulting on the same problem.

![recover](https://user-images.githubusercontent.com/55515252/108432198-c2f19980-7222-11eb-943e-321bbf03ef24.gif)
![recover-console](https://user-images.githubusercontent.com/55515252/108432208-c6852080-7222-11eb-8a6f-88704e63e22d.gif)

**Comment by reidrankin** [comment]
I can't reproduce this, so I'm hoping it's fixed. (In any case this really sounds like an issue with the React code rather than hdwallet itself, so if it's still a problem we should fix it as part of Axiom.)
