### ISSUE TITLE
Node v16 support?

### ISSUE THREAD

**Issue by taylorjdawson** [shapeshift/hdwallet#307]
Curious if we can use this on v16 of Node. Currently the `.nvmrc` only allows up to v14 but wondering if that can be changed.

**Comment by reidrankin** [comment]
Pretty sure it can be. Those lines are historical artifacts and last I checked consensus was they were dumb and should go.

**Comment by taylorjdawson** [comment]
@reidrankin Should I open a PR to amend the `.nvmrc`? I keep getting this error with yarn and have to switch node versions every time:
![image](https://user-images.githubusercontent.com/29665732/126844859-8a13d2d0-2cf1-4c5e-89f3-36c74b83f294.png)

**Comment by reidrankin** [comment]
It's not the .nvmrc itself -- it's the engine specifier in the package.json files. Looks like 1.15.2 was the last version before we took those out; bump up to latest and you should be good to go.

**Comment by reidrankin** [comment]
This should be fixed in versions after 1.15.2; closing. Feel free to re-open if you still have this issue.
