### ISSUE TITLE
Fix KeepKey hashes

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/hdwallet#487]
When reading the resolved promise from `KeepKeyHDWallet`'s `getFeatures` method, the objects `bootloaderHash` and `firmwareHash` values are incorrect.

The values are not valid SHA-256 hashes, and instead look like: `5F9Yf7B1M9gyVIQC0OcdjoI0iB2lTYbEtpnCimSCsO4=`.

**Comment by mrnerdhair** [comment]
That's 32 bytes, it's just encoded as base64 instead of hex; have we confirmed the underlying hash is actually wrong?
