### ISSUE TITLE
Same `Device not initialized` event triggered for wiped KK & awaiting passphrase

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/hdwallet#504]
At the moment it's difficult to distinguish between a KeepKey that was been wiped and needs to be initialized vs a KeepKey that is initialized with a passphrase and is waiting on a passphrase to be entered - the event for both is the same.

<img width="579" alt="Screen Shot 2022-04-06 at 12 58 19 pm" src="https://user-images.githubusercontent.com/97164662/162110239-6260b84e-0c52-400e-af7e-5f9d24942cc7.png">

Can we separate these into two distinct events?

**Comment by markrypt0** [comment]
This is not a bug in keepkey, it is designed to work this way. Hdwallet needs to work around this feature.

**Comment by 0xApotheosis** [comment]
As this directly relates to https://github.com/shapeshift/web/issues/1607, which it sounds like we have a path forward on, I'll close this issue.
