### ISSUE TITLE
Add cosmos support for HDWallet Ledger

### ISSUE THREAD

**Issue by theoboldfrazier** [shapeshift/hdwallet#539]
Currently, keplr doesn't work with ledger because hdwallet-ledger has not been updated to support cosmos.

**Comment by cjthompson** [comment]
Why would `hdwallet-ledger` need to be updated? `hdwallet-keplr` returns a `KeplrHDWallet` instance and all communications go through the keplr extension. `hdwallet-ledger` is used to directly pair a ledger device and we haven't added support for that.

**Comment by 0xdef1cafe** [comment]
closing as no one has complained about this, reopen if that changes
