### ISSUE TITLE
Remove unused type guards

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/hdwallet#549]
### Overview

We define wallet methods as type guards in `hdwallet-core`

However, we don't use them as type guards but only as regular utility methods to check for feature detection e.g

https://github.com/shapeshift/hdwallet/blob/9ada7ded938f7a8ee752517523a724d6a18d5f3e/packages/hdwallet-core/src/wallet.ts#L120-L122

We should remove the unused type guard in all these methods.

### References and additional details

hdwallet-core methods implementations:

https://github.com/shapeshift/hdwallet/blob/master/packages/hdwallet-core/src/wallet.ts

### Acceptance Criteria

- The hdwallet-core type guards are removed

**Comment by 0xApotheosis** [comment]
Thank you for this @gomesalexandre!
