### ISSUE TITLE
Support AVAX (and other chain signing) on keepkey

### ISSUE THREAD

**Issue by BitHighlander** [shapeshift/hdwallet#557]
### Overview

hdwallet-keepkey package currently is hard coded to Ethereum mainnet.

https://github.com/shapeshift/hdwallet/blob/master/packages/hdwallet-keepkey/src/ethereum.ts#L151

Producing the following error if you attempt to sign AVAX tx

```
e:  Error: Incompatible EIP155-based V 86264 and chain id 1. See the Common parameter of the Transaction constructor to set the chain id.
```

### References and additional details

sample tx payload

** unsignedTx HDwalletpayload:  

```{"addressNList":[2147483692,2147483708,2147483648,0,0],"nonce":"0x19","gasPrice":"0x35a315d30","gasLimit":"0x13880","value":"0x38d7ea4c68000","to":"0xC3aFFff54122658b89C31183CeC4F15514F34624","chainId":"43114"}```

### Acceptance Criteria

A.C. support signing transactions with chainId's other then 1

**Comment by foufrix** [comment]
Add integration test at https://github.com/shapeshift/hdwallet/blob/master/packages/hdwallet-keepkey/src/ethereum.ts#L151
=> prove that the chainid will not be changed back to 1 on ethsigntx calls
