### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by Mrtenz** [shapeshift/hdwallet#6]
The link to the documentation in the `README.md` (https://shapeshift.github.io/HDWallet/index.html) doesn't seem to work. It results in a 404 error.

**Comment by keepkeyjon** [comment]
Good catch. I forgot to set that up again after we open sourced this.

**Comment by keepkeyjon** [comment]
#77 fixes the broken link (by deleting it)

I'd still like to fix the docs build though, so let's leave this open.
