### ISSUE TITLE
Request: Create HDWallet web and node specific builds

### ISSUE THREAD

**Issue by dviramontes** [shapeshift/hdwallet#79]
As a consumer of HDWallet, I would like to be able to install and use a web friendly version of the library.

We could potentially have 3 builds
- hdwallet.web.js (web friendly version)
- hdwallet.node.js (native module for node projects)
- [hdwarellet.umd.js](https://github.com/umdjs/umd)(what it does now)

**Comment by taylorjdawson** [comment]
@dviramontes I agree! Do you have an implementation in mind? Would love to help out with this, currently having issues using this in browser.
