### ISSUE TITLE
Add npm install instructions.

### ISSUE THREAD

**Issue by MicahZoltu** [shapeshift/hdwallet#8]
While `yarn add @shapeshiftoss/hdwallet` may do something useful (not sure, I don't use yarn), `npm add @shapeshiftoss/hdwallet` just errors.  A glance at NPM suggests there are actually a bunch of different libraries that all start with `@shapeshiftoss/hdwallet` but have different suffixes.

**Comment by keepkeyjon** [comment]
That is expected. We don't ship HDWallet as a single package, but rather as a collection of them. This allows clients to bundle just the parts they need in their app, keeping download sizes for web apps small.

**Comment by keepkeyjon** [comment]
Looks like our readme has bad instructions.
